### ISSUE TITLE
Custom nginx.conf with SSL not working

### ISSUE THREAD

**Issue by bhushankumarl** [cloudfoundry/staticfile-buildpack#127]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
```
{
   "name": "Bluemix",
   "build": "270019",
   "support": "http://ibm.biz/bluemix-supportinfo",
   "version": 0,
   "description": "IBM Bluemix",
   "authorization_endpoint": "https://login.eu-gb.bluemix.net/UAALoginServerWAR",
   "token_endpoint": "https://uaa.eu-gb.bluemix.net",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.92.0",
   "app_ssh_endpoint": "ssh.eu-gb.bluemix.net:2222",
   "app_ssh_host_key_fingerprint": "c7:1f:89:2a:62:3b:78:a9:08:c9:33:81:fb:39:26:da",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.eu-gb.bluemix.net:443",
   "user": "30e93317-b5af-4b47-978a-fb1f0f855a6a"
}
```

```
cf version 6.33.0+a345ea34d.2017-11-20
```
What version of the buildpack you are using?
staticfile_buildpack

If you were attempting to accomplish a task, what was it you were attempting to do?
I am not able to start the server using custom nginx file which does also include the SSL.

What did you expect to happen?
The server should work with https URL.

What was the actual behavior?
```
   2017-12-08T19:02:21.31+0530 [APP/PROC/WEB/0] ERR + /home/vcap/app/start_logging.sh
   2017-12-08T19:02:21.31+0530 [APP/PROC/WEB/0] ERR + nginx -p /home/vcap/app/nginx -c /home/vcap/app/nginx/conf/nginx.conf
```
Right now it's thwoing above error after deployment.

Please confirm where necessary:
Here is the contain of the custom nginx file.
```
worker_processes 1;
daemon off;

error_log <%= ENV["APP_ROOT"] %>/nginx/logs/error.log;
events { worker_connections 1024; }

http {
  log_format cloudfoundry '$http_x_forwarded_for - $http_referer - [$time_local] "$request" $status $body_bytes_sent';
  access_log <%= ENV["APP_ROOT"] %>/nginx/logs/access.log cloudfoundry;
  default_type application/octet-stream;
  include mime.types;
  sendfile on;
  gzip on;
  tcp_nopush on;
  keepalive_timeout 30;

  server {
    listen <%= ENV["PORT"] %>;
    server_name localhost;

    ssl on;
    ssl_certificate <%= ENV["APP_ROOT"] %>/public/nginx.crt;
    ssl_certificate_key <%= ENV["APP_ROOT"] %>/public/nginx.key;


    location / {
      root <%= ENV["APP_ROOT"] %>/public;
      try_files $uri $uri/ /index.html =404;
      index index.html index.htm Default.htm;
    }
  }
}
```

Here is the manifest.yml
```
applications:
- name: amf-ui
  path: dist
  random-route: true
  memory: 512M
  buildpack: staticfile_buildpack
  env:
    # Use Google DNS by default
    NGINX_RESOLVER: 8.8.8.8
    #Enforce https is used (using x_forwarded_proto check) .Default: enabled
    FORCE_HTTPS: false
    #For AMF-UI only : App Level ENVs can be set from the .gitlab-ci.yml
```

I am uploading ngix.conf, nginx.crt and nginx.key inside the 'dist' folder
