### ISSUE TITLE
[Question] Env variable not taken in account

### ISSUE THREAD

**Issue by vykimo** [cloudfoundry/staticfile-buildpack#165]
Hi,
I'm deploying static files (html, css, js) on IBM cloud with that command : 
```
cf push "${CF_APP}" -f manifests/front_dev.yml -b https://github.com/cloudfoundry/staticfile-buildpack.git
```
In my ```front_dev.yml``` I have this : 
```
---
applications:
  - name: xxxx-xxx-v2-dev
    memory: 256M
    instances: 1
    env:
      BACK_END_URL: https://xxx-xxxx-v2-dev-back.eu-de.mybluemix.net/api
```

But when I'm on my web browser and I go to my web page I got this on the console :
```
APP_URL: "undefined"
​
CLIENT: true
​
DEV: false
​
MODE: "spa"
​
NODE_ENV: "production"
​
PROD: true
​
SERVER: false
​
VUE_ROUTER_BASE: ""
​
VUE_ROUTER_MODE: "hash"
```

So my env variable BACK_END_URL is not appearing...

Do you have an idea why ?
Thanks in advance
