### ISSUE TITLE
build commands

### ISSUE THREAD

**Issue by afeld** [cloudfoundry/staticfile-buildpack#64]
A question just came up of "how would I host a Jekyll site on Cloud Foundry?", and it's not obvious about the best way to have Cloud Foundry build a static site (for Jekyll, Hugo, etc.), as opposed to simply hosting the precompiled files. What's the best way to do this?

**Comment by ykhadilkar-rei** [comment]
For Jekyll, just need to add manifest.yml file. Below is my sample file 
```
---
applications:
- name: fbo-guide
  memory: 64M
  path: _site/
  buildpack: https://github.com/cloudfoundry/staticfile-buildpack.git
  env:
    FORCE_HTTPS: true
```
